### PR TITLE
Polish translate of weapons.phrases.txt

### PR DESCRIPTION
**Pull request by Nevvy**
Polish translate of weapons.phrases.txt

### CODE REVIEW

**Comment by wasyady** [comment]
Hungarian translate 

[weapons.phrases.txt](https://github.com/kaganus/weapons/files/1117211/weapons.phrases.txt)

**Comment by kaganus** [comment]
Used the one from https://forums.alliedmods.net/showpost.php?p=2535749&postcount=76 for Polish translation, as it seemed a little better (according to the google translate, plus the accents).

Using the Hungarian translation posted here.

**Comment by wasyady** [comment]
I find a problem.

	{
		"hu**0**"	"Megnövelés %d%%-kal"
	}

Here's the fixed version!

[weapons.phrases.txt](https://github.com/kaganus/weapons/files/1157348/weapons.phrases.txt)

**Comment by kaganus** [comment]
noted

**Pull request closed without merging**
